"""empty message

Revision ID: 888e216f6bfa
Revises: f51a301d973b
Create Date: 2025-12-02 14:34:30.789084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888e216f6bfa'
down_revision = 'f51a301d973b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
